_target_: lightning.pytorch.trainer.Trainer

default_root_dir: ${paths.output_dir}

min_epochs: 100 # 防止过早停止
max_epochs: 500

accelerator: gpu
devices: 1

# 混合精度训练以加速
precision: 16

# 每N个训练周期执行一次验证
check_val_every_n_epoch: 3

# 设为True以确保结果确定性
# 会降低训练速度，但比仅设置随机种子更可复现
deterministic: True
