# https://www.tensorflow.org/tensorboard/

tensorboard:
  _target_: lightning.pytorch.loggers.tensorboard.TensorBoardLogger
  save_dir: "/root/tf-logs/"
  name: null
  log_graph: False
  default_hp_metric: True
  prefix: ""
  # version: ""
