# @package _global_

# 在此处指定默认配置
# defaults 的顺序决定了配置文件的覆盖顺序
defaults:
  - _self_
  - data: fusion_data
  - model: fusion_module
  - callbacks: default
  - logger: tensorboard # 在此处设置 logger，或通过命令行设置（如 `python train.py logger=tensorboard`）
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default

  # 实验配置用于对特定超参数进行版本控制
  # 例如：针对特定模型和数据模块的最佳超参数
  - experiment: null

  # 超参数优化的配置
  - hparams_search: null

  # 可选的本地配置，用于机器/用户的特定设置
  # 该配置是可选的，不需要存在，并且不纳入版本控制
  - optional local: default

  # 调试配置（可通过命令行启用，如 `python train.py debug=default`）
  - debug: null

# 任务名称，决定输出目录路径
task_name: "train"

# 用于标记实验，便于识别
# 可以在实验配置中覆盖
# 也可通过命令行覆盖，如 `python train.py tags="[first_tag, second_tag]"`
tags: ["dev"]

# 设为 False 可跳过模型训练
train: True

# 在测试集上评估，使用训练过程中获得的最佳模型权重
# lightning 会根据 checkpoint 回调中指定的指标选择最佳权重
test: False

# 提供 checkpoint 路径以恢复训练
ckpt_path: null

# pytorch、numpy 和 python.random 的随机数生成器种子
seed: 42
